const data = {
  products: [
    {
      name: 'Free Shirt',
      slug: 'free-shirt',
      category: 'shirts',
      image: '/images/shirt1.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Shirt',
      slug: 'fit-shirt',
      category: 'shirts',
      image: '/images/shirt2.jpg',
      price: '70',
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'shirts',
      image: '/images/shirt3.jpg',
      price: '90',
      brand: 'Raymond',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Golf pants',
      slug: 'golf-pants',
      category: 'pants',
      image: '/images/pants1.jpg',
      price: '70',
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular pant',
    },
  ],
};

export default data;
